---
version: "3.8"

services:
  simplesrv:
    build:
      context: simplesrv/
      dockerfile: Dockerfile
    container_name: simplesrv
    ports:
      - 8080:8080
  beyla:
    image: grafana/beyla:latest
    container_name: beyla
    pid: "service:simplesrv"
    privileged: true
    ports:
      - 9400:9400
    environment:
      BEYLA_PROMETHEUS_PORT: 9400
      BEYLA_OPEN_PORT: 8080

  prometheus:
    #image: prom/prometheus:latest
    image: prom/prometheus:v3.0.0-beta.1
    container_name: prometheus
    volumes:
      - ./etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-storage:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - beyla

  grafana:
    image: grafana/grafana:11.3.0-ubuntu
    container_name: grafana
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./etc/grafana:/etc/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false

  k6:
    image: loadimpact/k6:latest
    container_name: k6
    volumes:
      - ./k6/load_test.js:/k6/load_test.js
    depends_on:
      - simplesrv
    command: run --out json /k6/load_test.js
    restart: unless-stopped

  loki:
    image: grafana/loki:2.9.10
    container_name: loki
    ports:
      - "3100:3100"
      - "9096:9096"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./etc/loki:/etc/loki
      - loki-data:/loki
    healthcheck:
      test: ["CMD-SHELL", "wget -q --tries=1 -O- http://localhost:3100/ready || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./etc/promtail/docker-config.yml:/etc/promtail/docker-config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/docker-config.yml

volumes:
  grafana-storage:
  prometheus-storage:
  loki-data:
