configs:
  grafana_config:
    content: |
      [feature_toggles]
      enable = true
      exploreMetrics = true
  grafana_datasources:
    content: |-
      apiVersion: 1
      datasources:
      - access: "proxy"
        basicAuth: false
        isDefault: true
        name: "prometheus"
        type: "prometheus"
        uid: "prometheus"
        url: "http://prometheus:9090"
      - access: "proxy"
        basicAuth: false
        isDefault: false
        name: "loki"
        orgId: 1
        type: "loki"
        uid: "loki"
        url: "http://loki:3100"
        version: 1
  loki_config:
    content: |-
      auth_enabled: false
      common:
        path_prefix: "/loki"
        replication_factor: 1
        ring:
          instance_addr: "127.0.0.1"
          kvstore:
            store: "inmemory"
      limits_config:
        ingestion_burst_size_mb: 64
        ingestion_rate_mb: 32
        max_cache_freshness_per_query: "10m"
        max_global_streams_per_user: 5000
        max_line_size: "2MB"
        per_stream_rate_limit: "32MB"
        per_stream_rate_limit_burst: "64MB"
        reject_old_samples: true
        reject_old_samples_max_age: "168h"
        volume_enabled: true
      ruler:
        storage:
          local:
            directory: "/loki/rules"
          type: "local"
      schema_config:
        configs:
        - from: "2020-05-15"
          index:
            period: "24h"
            prefix: "index_"
          object_store: "filesystem"
          schema: "v13"
          store: "tsdb"
      server:
        http_listen_port: 3100
      storage_config:
        filesystem:
          directory: "/loki/chunks"
      table_manager:
        retention_deletes_enabled: true
        retention_period: "672h"
  prometheus_config:
    content: |-
      global:
        scrape_interval: "15s"
      scrape_configs:
      - job_name: "beyla"
        static_configs:
        - targets:
          - "beyla:9400"
  promtail_config:
    content: |-
      clients:
      - url: "http://loki:3100/loki/api/v1/push"
      positions:
        filename: "/tmp/positions.yaml"
      scrape_configs:
      - docker_sd_configs:
        - host: "unix:///var/run/docker.sock"
          refresh_interval: "5s"
        job_name: "docker"
        relabel_configs:
        - regex: "/(.*)"
          source_labels:
          - "__meta_docker_container_name"
          target_label: "container"
        - regex: "/(.*)"
          source_labels:
          - "__meta_docker_container_name"
          target_label: "service_name"
        - source_labels:
          - "__meta_docker_container_log_stream"
          target_label: "logstream"
        - source_labels:
          - "__meta_docker_container_label_logging_jobname"
          target_label: "job"
      server:
        http_listen_address: "0.0.0.0"
        http_listen_port: 9080
