version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app
  prometheus:
    image: prom/prometheus:v2.37.0
    volumes:
      - ./etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - web
  grafana:
    #image: grafana/grafana:10.0.12
    #image: us.gcr.io/hosted-grafana/hosted-grafana-pro:11.1.0-69181
    image: grafana/grafana:11.0.0-preview-ubuntu
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./etc/grafana:/etc/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
  loadtester:
    image: loadimpact/k6:latest
    volumes:
      - ./k6/load_test.js:/scripts/load_test.js
    depends_on:
      - web
    command: run /scripts/load_test.js
    restart: always

volumes:
  grafana-storage:
