{
 "title": "GnFMendoza demo#1",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "k6: max request time by method without errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by (method) (k6_http_req_duration_max{error=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "k6: error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (method) (k6_http_req_failed_rate)\n/\nscalar(sum (rate(k6_http_reqs_total[2m])))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "k6: cli vs srv observed method rate",
   "type": "xychart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (method)(rate(k6_http_reqs_total[2m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(demo_app_http_requests_total[2m])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}