all:
	@echo make up-build
	@echo make up
	@echo make down
	@echo make log

up-build:
	docker-compose up -d --build

up:
	docker-compose up -d

down:
	docker-compose down

log:
	docker-compose logs -f
