{
 "title": "GnFMendoza demo#0",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Requests rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (job, path, method) (rate(path_method:demo_app_requests_total[2m]))\n"
    }
   ]
  },
  {
   "title": "Requests latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (job, path, method) (rate(flask_http_request_duration_seconds_sum[2m]))\n/\nsum by (job, path, method) (rate(flask_http_request_duration_seconds_count[2m]))"
    }
   ]
  },
  {
   "title": "Requests latency percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(flask_http_request_duration_seconds_bucket[1m])) by (job, path, method,le))",
     "legendFormat": "p95 {{job}} {{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Requests latency percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(flask_http_request_duration_seconds_bucket[1m])) by (job, path, method,le))",
     "legendFormat": "p50 {{job}} {{method}} {{path}}"
    }
   ]
  }
 ]
}